
name: Gradle Build and Release on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Grant gradlew execute permission
        run: icacls gradlew /grant Everyone:F
        
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Create libs directory and placeholder jar
        run: |
          New-Item -ItemType Directory -Force -Path libs
          if (-not (Test-Path "libs\newboy-1.0.0.mirai2.jar")) {
            # Create a minimal placeholder jar file
            Add-Type -AssemblyName System.IO.Compression.FileSystem
            $zipPath = "libs\newboy-1.0.0.mirai2.jar"
            [System.IO.Compression.ZipFile]::CreateFromDirectory((New-Item -ItemType Directory -Force -Path "temp_jar").FullName, $zipPath)
            Remove-Item -Recurse -Force "temp_jar"
          }
            
      - name: Build with Gradle
        run: .\gradlew.bat build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-output
          path: build/libs/*.jar
          retention-days: 7

      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          generate_release_notes: true
